default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production: &production
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

# Rails 8 Solid Queue
queue:
  <<: *production

# Rails 8 Solid Cache
cache:
  <<: *production

# Rails 8 Solid Cable
cable:
  <<: *production
